# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Aikizen"
license = "MIT"
licenselink = "https://github.com/aikithoughts/hugo-aikizen-theme/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/aikithoughts/hugo-aikizen-theme"
tags = []
features = []
min_version = "0.21"

[author]
  name = "Aikithoughts"
  homepage = "https://aikithoughts.github.io"
